export const TRADE_OPTIONS = [
  'Asbestos / Environmental /Lead Abatement',
  'Asphalt',
  'Boilermaker',
  'Bricklayers / Mason / Tuckpointing',
  'Carpenter - Interior',
  'Carpenter - Ruff / Framing',
  'Carpet Installer',
  'Caulking, Horizontal',
  'Caulking, Vertical',
  'CCTV',
  'Cement & Concrete Finisher',
  'Cement Masons',
  'Concrete',
  'Concrete Cutting',
  'Demolition',
  'Dredge Operator',
  'Drywall',
  'Earthwork / Excuvation /Site Work',
  'EIFS Installer',
  'Electrical',
  'Elevator Mechanic',
  'Engineering Firm',
  'Equipment Operator',
  'Erosion Control',
  'EV Stations',
  'Fencer/Fence Erector',
  'Fire Protection',
  'Flooring, Seal & Polish',
  'General Contracting',
  'Glasswork / Glazier',
  'Hauling & Dumping',
  'Heating/Air Conditioning (HVAC)',
  'Janitorial / Clean up, Construction Site',
  'Laborers',
  'Landscaping',
  'OPERATING ENGINEERS',
  'Painters',
  'Paving / Pavement Marking',
  'Plasterers',
  'Plumber',
  'PLUMBERS',
  'Professional Service Firm',
  'ROOFERS',
  'Safety',
  'Security',
  'Shoring',
  'Steel / Structural/other',
  'Traffic Control',
  'Transportation / Trucking',
  'TUCKPOINTERS',
  'Undergroumd Sewers & Drains / Water and Sewer Construction',
  'Utility Lines',
  'Waterproofing',
  'Welders'
] as const;